[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm']

[phases.install]
cmds = [
  'cd frontend && npm install',
  'cd frontend && npx vite build',
  'cd backend && npm install --production'
]

[start]
cmd = 'cd backend && node server.js'

