[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd frontend && npm install && npm run build',
  'cd backend && npm install --production'
]

[start]
cmd = 'cd backend && node server.js'

