[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd frontend && npm ci && npx vite build',
  'cd backend && npm ci --production'
]

[start]
cmd = 'cd backend && node server.js'

