[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'cd ../frontend && npm install',
  'cd ../frontend && npm run build',
  'cd ../backend && npm install --production'
]

[start]
cmd = 'node server.js'

